apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edugov-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: edugov-backend
            port:
              number: 5001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edugov-frontend
            port:
              number: 3000
